# Generated by Django 4.2.17 on 2024-12-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='user',
        ),
    ]
